version: '3.7'

services:
  proxy-crawler:
    image: "itmeng2018/proxy-app:v0.1.0"
    container_name: proxy-crawler
    restart: always
    links:
      - proxy-redis
    entrypoint: python crawler.py
    environment:
      - "DB_CONN=redis://@proxy-redis:6379/0"
      - "HTTP_URL=http://httpbin.org"
      - "HTTPS_URL=https://www.qq.com"

  proxy-server:
    image: "itmeng2018/proxy-app:v0.1.0"
    container_name: proxy-server
    restart: always
    links:
      - proxy-redis
    entrypoint: python server.py
    environment:
      - "DB_CONN=redis://@proxy-redis:6379/0"
    ports:
      - "5000:5000"

  proxy-redis:
    image: "redis"
    restart: always
    container_name: proxy-redis
    ports:
      - "6379:6379"
